spring:
  cache:
    type: redis
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 1234
  sql:
    init:
      mode: always
  jackson:
    serialization:
      write-dates-as-timestamps: false
